### PR TITLE
Update runwith.py

### PR DESCRIPTION
**Pull request by ilmanowar**
Hello Waldner, I am Massimo,
the added line prevents, on some machines, the error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2
I see it is related to the encodings enabled in the machine.
Thank you.
Bye.

### CODE REVIEW

**Comment by waldner** [comment]
I'm not sure what adding a comment in the file does. I'd like to be able to reproduce the problem. Which OS? Which Python version? What's the text being passed?

**Comment by waldner** [comment]
Ok, I've been able to reproduce the problem. It happens with Python2 when passing non strictly ASCII text. Looking into it.

**Comment by waldner** [comment]
Check out commit https://github.com/waldner/Firefox-RunWith/commit/3a2b67d20286f661e65c0ab59ea5867cf2706c57, it should work, otherwise let me know.

**Comment by ilmanowar** [comment]
It seems to be equivalent.
Mine was a general directive, in your case it is local directive (just for
the instruction).
It works perfectly in both cases.

Thank you.
Best regards,
Massimo

Massimo

____________________________________________________________________

PGP key id 0xC018209F
ilmanowar.altervista.org/Massimo_L._Filograno__0xC018209F__pub.asc
ICQ#: 495216115
Skype: ilmanowar
Mobile +39.392.massimo = +39.392.6277466
Voicemail: +3906916504820
Fax:  +3906233290900
Fax:  +3909922098085
____________________________________________________________________


2018-05-10 23:55 GMT+03:00 waldner <notifications@github.com>:

**Comment by waldner** [comment]
Can you give a pointer in the Python documentation to the syntax you used? I'm curious since it didn't work for me as written by you.

**Comment by ilmanowar** [comment]
Have a look here:

https://www.python.org/dev/peps/pep-0263/

It must be in the begin, maybe in your try it wasn't.

Massimo

____________________________________________________________________

PGP key id 0xC018209F
ilmanowar.altervista.org/Massimo_L._Filograno__0xC018209F__pub.asc
ICQ#: 495216115
Skype: ilmanowar
Mobile +39.392.massimo = +39.392.6277466
Voicemail: +3906916504820
Fax:  +3906233290900
Fax:  +3909922098085
____________________________________________________________________


2018-05-11 12:46 GMT+03:00 waldner <notifications@github.com>:

**Comment by waldner** [comment]
Well, in your patch it was on line 7 :-) I didn't know it, thanks.
However it looks to me that is just to declare the source file encoding and it doesn't affect how encode()/decode() work on external input. Indeed, I've tried putting the directive on line 2 as follows: `# encoding=utf8' and `# encoding=utf-8` (without changing the call to `.decode()`) and I still got the ` 'ascii' codec can't decode byte` error. I'm not sure how it worked for you. Anyway, I'm glad it's fixed now. Thanks!

**Comment by waldner** [comment]
Interesting. Note that Python 3 introduced many changes regarding string and unicode management. The old `runwith.py` (ie, the one with `.decode()`) worked fine with Python 3, while it failed on Python 2 (probably because in Python 3 everything is unicode already, but not in Python 2). Perhaps you had different Python versions on your machines?

**Pull request closed without merging**
